export default [
    {
        internshipId: 0,
        roleName: "Node.Js Developer",
        companyName: "Parallax Labs",
        companyLogo: "https://parallax.co.in/images/logo1_white.png",
        stipend: 20000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 1,
        roleName: "Full Stack Developer",
        companyName: "Anchors",
        companyLogo: "https://www.anchors.in/static/media/logo-invite-only.05788d79bfb2d37a65d2.png",
        stipend: 120000,
        experienceRequired: "6 months",
    },
    {
        internshipId: 2,
        roleName: "Junior Backend Developer",
        companyName: "Tech Innovations",
        companyLogo: "https://techinnovations.com/images/logo.png",
        stipend: 18000,
        experienceRequired: "8 months",
    },
    {
        internshipId: 3,
        roleName: "Frontend Developer",
        companyName: "Creative Minds",
        companyLogo: "https://creativeminds.com/images/logo.png",
        stipend: 16000,
        experienceRequired: "0.6 - 1 year",
    },
    {
        internshipId: 4,
        roleName: "Software Engineer",
        companyName: "Digital Solutions",
        companyLogo: "https://digitalsolutions.com/images/logo.png",
        stipend: 20000,
        experienceRequired: "10 months",
    },
    {
        internshipId: 5,
        roleName: "Junior Full Stack Developer",
        companyName: "ByteCrafters",
        companyLogo: "https://bytecrafters.io/images/logo.png",
        stipend: 25000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 6,
        roleName: "Junior Frontend Developer",
        companyName: "Web Wizards",
        companyLogo: "https://webwizards.com/images/logo.png",
        stipend: 23000,
        experienceRequired: "10 months",
    },
    {
        internshipId: 7,
        roleName: "Junior Backend Engineer",
        companyName: "CodeMasters",
        companyLogo: "https://codemasters.com/images/logo.png",
        stipend: 24000,
        experienceRequired: "6 months",
    },
    {
        internshipId: 8,
        roleName: "Web Developer",
        companyName: "Tech Innovators",
        companyLogo: "https://techinnovators.com/images/logo.png",
        stipend: 24000,
        experienceRequired: "10 months",
    },
    {
        internshipId: 9,
        roleName: "Junior Software Developer",
        companyName: "Innovative Solutions",
        companyLogo: "https://innovativesolutions.com/images/logo.png",
        stipend: 22000,
        experienceRequired: "9 months",
    },
    {
        internshipId: 10,
        roleName: "Frontend Engineer",
        companyName: "WebCrafters",
        companyLogo: "https://webcrafters.io/images/logo.png",
        stipend: 23000,
        experienceRequired: "10 months",
    },
    {
        internshipId: 11,
        roleName: "Junior UI/UX Developer",
        companyName: "Design Innovations",
        companyLogo: "https://designinnovations.com/images/logo.png",
        stipend: 22000,
        experienceRequired: "9 months",
    },
    {
        internshipId: 12,
        roleName: "Junior Mobile App Developer",
        companyName: "App Wizards",
        companyLogo: "https://appwizards.com/images/logo.png",
        stipend: 23000,
        experienceRequired: "10 months",
    },
    {
        internshipId: 13,
        roleName: "Junior Frontend Engineer",
        companyName: "Web Innovators",
        companyLogo: "https://webinnovators.com/images/logo.png",
        stipend: 22000,
        experienceRequired: "9 months",
    },
    {
        internshipId: 14,
        roleName: "Junior Software Engineer",
        companyName: "Innovative Coders",
        companyLogo: "https://innovativecoders.com/images/logo.png",
        stipend: 24000,
        experienceRequired: "11 months",
    },
    {
        internshipId: 15,
        roleName: "Junior Full Stack Engineer",
        companyName: "Byte Innovations",
        companyLogo: "https://byteinnovations.io/images/logo.png",
        stipend: 25000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 16,
        roleName: "Junior Mobile Developer",
        companyName: "AppCrafters",
        companyLogo: "https://appcrafters.com/images/logo.png",
        stipend: 23000,
        experienceRequired: "10 months",
    },
    {
        internshipId: 17,
        roleName: "Junior Web Developer",
        companyName: "WebMasters",
        companyLogo: "https://webmasters.com/images/logo.png",
        stipend: 22000,
        experienceRequired: "9 months",
    },
    {
        internshipId: 18,
        roleName: "Junior Mobile App Developer",
        companyName: "App Wizards",
        companyLogo: "https://appwizards.com/images/logo.png",
        stipend: 27000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 19,
        roleName: "Junior Backend Developer",
        companyName: "CodeCrafters",
        companyLogo: "https://codecrafters.com/images/logo.png",
        stipend: 24000,
        experienceRequired: "11 months",
    },
    {
        internshipId: 20,
        roleName: "Junior UI/UX Designer",
        companyName: "Design Wizards",
        companyLogo: "https://designwizards.com/images/logo.png",
        stipend: 22000,
        experienceRequired: "9 months",
    },
    {
        internshipId: 21,
        roleName: "Junior Frontend Developer",
        companyName: "Web Wizards",
        companyLogo: "https://webwizards.com/images/logo.png",
        stipend: 24000,
        experienceRequired: "10 months",
    },
    {
        internshipId: 22,
        roleName: "Junior Backend Engineer",
        companyName: "CodeMasters",
        companyLogo: "https://codemasters.com/images/logo.png",
        stipend: 25000,
        experienceRequired: "11 months",
    },
    {
        internshipId: 23,
        roleName: "Web Developer",
        companyName: "Tech Innovators",
        companyLogo: "https://techinnovators.com/images/logo.png",
        stipend: 25000,
        experienceRequired: "11 months",
    },
    {
        internshipId: 24,
        roleName: "Junior Software Developer",
        companyName: "Innovative Solutions",
        companyLogo: "https://innovativesolutions.com/images/logo.png",
        stipend: 23000,
        experienceRequired: "10 months",
    },
    {
        internshipId: 25,
        roleName: "Frontend Engineer",
        companyName: "WebCrafters",
        companyLogo: "https://webcrafters.io/images/logo.png",
        stipend: 24000,
        experienceRequired: "11 months",
    },
    {
        internshipId: 26,
        roleName: "Junior UI/UX Developer",
        companyName: "Design Innovations",
        companyLogo: "https://designinnovations.com/images/logo.png",
        stipend: 23000,
        experienceRequired: "10 months",
    },
    {
        internshipId: 27,
        roleName: "Junior Mobile App Developer",
        companyName: "App Wizards",
        companyLogo: "https://appwizards.com/images/logo.png",
        stipend: 24000,
        experienceRequired: "11 months",
    },
    {
        internshipId: 28,
        roleName: "Junior Frontend Engineer",
        companyName: "Web Innovators",
        companyLogo: "https://webinnovators.com/images/logo.png",
        stipend: 23000,
        experienceRequired: "10 months",
    },
    {
        internshipId: 29,
        roleName: "Junior Software Engineer",
        companyName: "Innovative Coders",
        companyLogo: "https://innovativecoders.com/images/logo.png",
        stipend: 25000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 30,
        roleName: "Junior Full Stack Engineer",
        companyName: "Byte Innovations",
        companyLogo: "https://byteinnovations.io/images/logo.png",
        stipend: 26000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 31,
        roleName: "Junior Mobile Developer",
        companyName: "AppCrafters",
        companyLogo: "https://appcrafters.com/images/logo.png",
        stipend: 24000,
        experienceRequired: "11 months",
    },
    {
        internshipId: 32,
        roleName: "Junior Web Developer",
        companyName: "WebMasters",
        companyLogo: "https://webmasters.com/images/logo.png",
        stipend: 23000,
        experienceRequired: "10 months",
    },
    {
        internshipId: 33,
        roleName: "Junior Backend Developer",
        companyName: "CodeCrafters",
        companyLogo: "https://codecrafters.com/images/logo.png",
        stipend: 25000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 34,
        roleName: "Junior UI/UX Designer",
        companyName: "Design Wizards",
        companyLogo: "https://designwizards.com/images/logo.png",
        stipend: 23000,
        experienceRequired: "10 months",
    },
    {
        internshipId: 35,
        roleName: "Junior Frontend Developer",
        companyName: "Web Wizards",
        companyLogo: "https://webwizards.com/images/logo.png",
        stipend: 24000,
        experienceRequired: "11 months",
    },
    {
        internshipId: 36,
        roleName: "Junior Backend Engineer",
        companyName: "CodeMasters",
        companyLogo: "https://codemasters.com/images/logo.png",
        stipend: 25000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 37,
        roleName: "Web Developer",
        companyName: "Tech Innovators",
        companyLogo: "https://techinnovators.com/images/logo.png",
        stipend: 25000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 38,
        roleName: "Junior Software Developer",
        companyName: "Innovative Solutions",
        companyLogo: "https://innovativesolutions.com/images/logo.png",
        stipend: 23000,
        experienceRequired: "11 months",
    },
    {
        internshipId: 39,
        roleName: "Frontend Engineer",
        companyName: "WebCrafters",
        companyLogo: "https://webcrafters.io/images/logo.png",
        stipend: 24000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 40,
        roleName: "Junior UI/UX Developer",
        companyName: "Design Innovations",
        companyLogo: "https://designinnovations.com/images/logo.png",
        stipend: 23000,
        experienceRequired: "11 months",
    },
    {
        internshipId: 41,
        roleName: "Junior Software Engineer",
        companyName: "CodeCrafters",
        companyLogo: "https://codecrafters.com/images/logo.png",
        stipend: 26000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 42,
        roleName: "Junior Full Stack Developer",
        companyName: "Byte Innovations",
        companyLogo: "https://byteinnovations.io/images/logo.png",
        stipend: 27000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 43,
        roleName: "Junior Mobile Developer",
        companyName: "AppCrafters",
        companyLogo: "https://appcrafters.com/images/logo.png",
        stipend: 25000,
        experienceRequired: "11 months",
    },
    {
        internshipId: 44,
        roleName: "Junior Web Developer",
        companyName: "WebMasters",
        companyLogo: "https://webmasters.com/images/logo.png",
        stipend: 24000,
        experienceRequired: "10 months",
    },
    {
        internshipId: 45,
        roleName: "Junior Backend Developer",
        companyName: "Tech Innovators",
        companyLogo: "https://techinnovators.com/images/logo.png",
        stipend: 26000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 46,
        roleName: "Junior UI/UX Designer",
        companyName: "Design Wizards",
        companyLogo: "https://designwizards.com/images/logo.png",
        stipend: 24000,
        experienceRequired: "10 months",
    },
    {
        internshipId: 47,
        roleName: "Junior Frontend Developer",
        companyName: "Web Wizards",
        companyLogo: "https://webwizards.com/images/logo.png",
        stipend: 25000,
        experienceRequired: "11 months",
    },
    {
        internshipId: 48,
        roleName: "Junior Backend Engineer",
        companyName: "CodeMasters",
        companyLogo: "https://codemasters.com/images/logo.png",
        stipend: 26000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 49,
        roleName: "Web Developer",
        companyName: "Tech Innovators",
        companyLogo: "https://techinnovators.com/images/logo.png",
        stipend: 27000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 50,
        roleName: "Junior Software Developer",
        companyName: "Innovative Solutions",
        companyLogo: "https://innovativesolutions.com/images/logo.png",
        stipend: 25000,
        experienceRequired: "11 months",
    },
    {
        internshipId: 51,
        roleName: "Frontend Engineer",
        companyName: "WebCrafters",
        companyLogo: "https://webcrafters.io/images/logo.png",
        stipend: 26000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 52,
        roleName: "Junior UI/UX Developer",
        companyName: "Design Innovations",
        companyLogo: "https://designinnovations.com/images/logo.png",
        stipend: 25000,
        experienceRequired: "11 months",
    },
    {
        internshipId: 53,
        roleName: "Junior Mobile App Developer",
        companyName: "App Wizards",
        companyLogo: "https://appwizards.com/images/logo.png",
        stipend: 26000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 54,
        roleName: "Junior Frontend Engineer",
        companyName: "Web Innovators",
        companyLogo: "https://webinnovators.com/images/logo.png",
        stipend: 25000,
        experienceRequired: "11 months",
    },
    {
        internshipId: 55,
        roleName: "Junior Software Engineer",
        companyName: "Innovative Coders",
        companyLogo: "https://innovativecoders.com/images/logo.png",
        stipend: 27000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 56,
        roleName: "Junior Full Stack Engineer",
        companyName: "Byte Innovations",
        companyLogo: "https://byteinnovations.io/images/logo.png",
        stipend: 28000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 57,
        roleName: "Junior Mobile Developer",
        companyName: "AppCrafters",
        companyLogo: "https://appcrafters.com/images/logo.png",
        stipend: 26000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 58,
        roleName: "Junior Web Developer",
        companyName: "WebMasters",
        companyLogo: "https://webmasters.com/images/logo.png",
        stipend: 25000,
        experienceRequired: "11 months",
    },
    {
        internshipId: 59,
        roleName: "Junior Backend Developer",
        companyName: "CodeCrafters",
        companyLogo: "https://codecrafters.com/images/logo.png",
        stipend: 27000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 60,
        roleName: "Junior UI/UX Designer",
        companyName: "Design Wizards",
        companyLogo: "https://designwizards.com/images/logo.png",
        stipend: 25000,
        experienceRequired: "11 months",
    },

    {
        internshipId: 61,
        roleName: "Junior Frontend Developer",
        companyName: "WebTech Solutions",
        companyLogo: "https://webtechsolutions.com/images/logo.png",
        stipend: 28000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 62,
        roleName: "Junior Backend Engineer",
        companyName: "TechGenius",
        companyLogo: "https://techgenius.com/images/logo.png",
        stipend: 29000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 63,
        roleName: "Web Developer",
        companyName: "CodeCraft",
        companyLogo: "https://codecraft.com/images/logo.png",
        stipend: 30000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 64,
        roleName: "Junior Software Developer",
        companyName: "InnoTech",
        companyLogo: "https://innotech.com/images/logo.png",
        stipend: 31000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 65,
        roleName: "Frontend Engineer",
        companyName: "TechCrafters",
        companyLogo: "https://techcrafters.com/images/logo.png",
        stipend: 19000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 66,
        roleName: "Junior UI/UX Developer",
        companyName: "DesignTech",
        companyLogo: "https://designtech.com/images/logo.png",
        stipend: 33000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 67,
        roleName: "Junior Mobile App Developer",
        companyName: "App Innovations",
        companyLogo: "https://appinnovations.com/images/logo.png",
        stipend: 21500,
        experienceRequired: "1 year",
    },
    {
        internshipId: 68,
        roleName: "Junior Frontend Engineer",
        companyName: "WebGenius",
        companyLogo: "https://webgenius.com/images/logo.png",
        stipend: 35000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 69,
        roleName: "Junior Software Engineer",
        companyName: "TechSolutions",
        companyLogo: "https://techsolutions.com/images/logo.png",
        stipend: 30000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 70,
        roleName: "Junior Full Stack Engineer",
        companyName: "ByteTech",
        companyLogo: "https://bytetech.com/images/logo.png",
        stipend: 17000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 71,
        roleName: "Junior Mobile Developer",
        companyName: "AppCraft",
        companyLogo: "https://appcraft.com/images/logo.png",
        stipend: 18000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 72,
        roleName: "Junior Web Developer",
        companyName: "WebInno",
        companyLogo: "https://webinno.com/images/logo.png",
        stipend: 12000,
        experienceRequired: "0-6 month",
    },
    {
        internshipId: 73,
        roleName: "Junior Backend Developer",
        companyName: "CodeInnovate",
        companyLogo: "https://codeinnovate.com/images/logo.png",
        stipend: 20000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 74,
        roleName: "Junior UI/UX Designer",
        companyName: "DesignCraft",
        companyLogo: "https://designcraft.com/images/logo.png",
        stipend: 14000,
        experienceRequired: "8 months",
    },
    {
        internshipId: 75,
        roleName: "Junior Frontend Developer",
        companyName: "WebTech Solutions",
        companyLogo: "https://webtechsolutions.com/images/logo.png",
        stipend: 27000,
        experienceRequired: "0-1 year",
    },
    {
        internshipId: 76,
        roleName: "Junior Backend Engineer",
        companyName: "TechGenius",
        companyLogo: "https://techgenius.com/images/logo.png",
        stipend: 13000,
        experienceRequired: "0-1 year",
    },
    {
        internshipId: 77,
        roleName: "Web Developer",
        companyName: "CodeCraft",
        companyLogo: "https://codecraft.com/images/logo.png",
        stipend: 14000,
        experienceRequired: "3 months",
    },
    {
        internshipId: 78,
        roleName: "Junior Software Developer",
        companyName: "InnoTech",
        companyLogo: "https://innotech.com/images/logo.png",
        stipend: 15000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 79,
        roleName: "Frontend Engineer",
        companyName: "TechCrafters",
        companyLogo: "https://techcrafters.com/images/logo.png",
        stipend: 13000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 80,
        roleName: "Junior UI/UX Developer",
        companyName: "DesignTech",
        companyLogo: "https://designtech.com/images/logo.png",
        stipend: 17000,
        experienceRequired: "1 year",
    },

    {
        internshipId: 81,
        roleName: "Junior Frontend Developer",
        companyName: "WebTech Solutions",
        companyLogo: "https://webtechsolutions.com/images/logo.png",
        stipend: 28000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 82,
        roleName: "Junior Backend Engineer",
        companyName: "TechGenius",
        companyLogo: "https://techgenius.com/images/logo.png",
        stipend: 19000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 83,
        roleName: "Web Developer",
        companyName: "CodeCraft",
        companyLogo: "https://codecraft.com/images/logo.png",
        stipend: 30000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 84,
        roleName: "Junior Software Developer",
        companyName: "InnoTech",
        companyLogo: "https://innotech.com/images/logo.png",
        stipend: 11000,
        experienceRequired: "0-1 year",
    },
    {
        internshipId: 85,
        roleName: "Frontend Engineer",
        companyName: "TechCrafters",
        companyLogo: "https://techcrafters.com/images/logo.png",
        stipend: 12000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 86,
        roleName: "Junior UI/UX Developer",
        companyName: "DesignTech",
        companyLogo: "https://designtech.com/images/logo.png",
        stipend: 23000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 87,
        roleName: "Junior Mobile App Developer",
        companyName: "App Innovations",
        companyLogo: "https://appinnovations.com/images/logo.png",
        stipend: 34000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 88,
        roleName: "Junior Frontend Engineer",
        companyName: "WebGenius",
        companyLogo: "https://webgenius.com/images/logo.png",
        stipend: 12000,
        experienceRequired: "fresher",
    },
    {
        internshipId: 89,
        roleName: "Junior Software Engineer",
        companyName: "TechSolutions",
        companyLogo: "https://techsolutions.com/images/logo.png",
        stipend: 36000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 90,
        roleName: "Junior Full Stack Engineer",
        companyName: "ByteTech",
        companyLogo: "https://bytetech.com/images/logo.png",
        stipend: 17000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 91,
        roleName: "Junior Mobile Developer",
        companyName: "AppCraft",
        companyLogo: "https://appcraft.com/images/logo.png",
        stipend: 16000,
        experienceRequired: "fresher",
    },
    {
        internshipId: 92,
        roleName: "Junior Web Developer",
        companyName: "WebInno",
        companyLogo: "https://webinno.com/images/logo.png",
        stipend: 19000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 93,
        roleName: "Junior Backend Developer",
        companyName: "CodeInnovate",
        companyLogo: "https://codeinnovate.com/images/logo.png",
        stipend: 12000,
        experienceRequired: "6 moths",
    },
    {
        internshipId: 94,
        roleName: "Junior UI/UX Designer",
        companyName: "DesignCraft",
        companyLogo: "https://designcraft.com/images/logo.png",
        stipend: 21000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 95,
        roleName: "Junior Frontend Developer",
        companyName: "WebTech Innovations",
        companyLogo: "https://webtechinnovations.com/images/logo.png",
        stipend: 12000,
        experienceRequired: "0-1 year",
    },
    {
        internshipId: 96,
        roleName: "Junior Backend Engineer",
        companyName: "Tech Innovations",
        companyLogo: "https://techinnovations.com/images/logo.png",
        stipend: 25000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 97,
        roleName: "Web Developer",
        companyName: "InnoCode",
        companyLogo: "https://innocode.com/images/logo.png",
        stipend: 14000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 98,
        roleName: "Junior Software Developer",
        companyName: "CodeSolutions",
        companyLogo: "https://codesolutions.com/images/logo.png",
        stipend: 26000,
        experienceRequired: "1 year",
    },
    {
        internshipId: 99,
        roleName: "Junior UI/UX Developer",
        companyName: "Design Innovations",
        companyLogo: "https://designinnovations.com/images/logo.png",
        stipend: 16000,
        experienceRequired: "1 year",
    },
    
];
